### ISSUE TITLE
Sign a pdf file with pfx certificate

### ISSUE THREAD

**Issue by joweste** [Advanon/pdf-signatures#4]
Please, I have a pfx certififcate with password, and a pdf file.
Can you give a sample showing  how to read the pfx certifficate with password and signing the pdf file?

Regards, 

Luiz

**Comment by pandomic** [comment]
Hi Luiz [pin @joweste], thanks for your interest to our library.

Could you please provide sample files so that we can take a look?

Thank you.

Best,
Vlad

**Comment by pandomic** [comment]
I'm closing the issue due to inactivity. Feel free to reopen in case new issues arise.
